### ISSUE TITLE
An import error occurs.

### ISSUE THREAD

**Issue by darkdarkcocoa** [bmaltais/kohya_ss#1939] opened 2024-02-07 04:13 UTC
When I finish all the installation process and run gui.bat, I get an error. 
I tried to solve the cause by googling but couldn't. 
Please help.

![cbab25833c0bebd5cfbfb0f4d9e6574ae8abbeb909c8fcc8550296d937c576f4](https://github.com/bmaltais/kohya_ss/assets/67269224/be19eadb-f0f9-4437-b367-d596dcfb8a54)

Traceback (most recent call last):
  File "C:\kohya_ss\kohya_gui.py", line 1, in <module>
    import gradio as gr
  File "C:\kohya_ss\venv\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "C:\kohya_ss\venv\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "C:\kohya_ss\venv\lib\site-packages\gradio\components\annotated_image.py", line 8, in <module>
    from gradio_client.documentation import document, set_documentation_group
ImportError: cannot import name 'set_documentation_group' from 'gradio_client.documentation' (C:\kohya_ss\venv\lib\site-packages\gradio_client\documentation.py)

**Comment by nathankrueger** [comment] 2024-02-07 04:17
This is a duplicate of: https://github.com/bmaltais/kohya_ss/issues/1938

**Comment by bmaltais** [comment] 2024-02-10 13:34
I don't observe this at my end... I will try to delete my venv and see if I get the same issue on a full setup.

Have you tried this? Have you tried deleting the venv folder and re-run setup? Does it give you the same error?

**Closed** 2024-05-01 11:13 UTC
