### ISSUE TITLE
Training extremely slow after updating

### ISSUE THREAD

**Issue by pulth** [bmaltais/kohya_ss#961] opened 2023-06-10 02:20 UTC
I hadn't used kohya_ss in a couple of months.

I did a fresh install using the latest version, tried with both pytorch 1 and 2 and did the acceleration optimizations from the setup.bat script. I now find that training loras with the same parameters and datasets I previously used has slowed down to a crawl, I would say it's a lot slower, where something that took 30 minutes previously now takes over 2 hours. I don't get any error messages (other than the missing 'triton' package if I use pytorch 2) so I'm quite lost as to what is going wrong in this situation.

Where could I have gone wrong? Should I manually install a new CUDA version? I have a GTX 1080, so I'm not using cuDNN.

**Comment by pulth** [comment] 2023-06-10 02:22
For reference, I'm training a test model on 12 images of a character at 125 steps each using batch size 2 and 512,512 resolution and get a training time of over 2 hours. Is this expected from a GPU like the 1080 with 8GB of VRAM?

**Comment by sumire608** [comment] 2023-06-10 02:23
If you have installed Nvidia driver 535.98, rollback to previous version. There's a bug with it.

**Comment by pulth** [comment] 2023-06-10 02:24
I did see there's issues with the newer NVIDIA drivers, so I'm currently using the 527.56 version.

**Comment by sumire608** [comment] 2023-06-10 02:28
Ok try to reduce batch to 1 then. 🤒

**Comment by Disorbs** [comment] 2023-06-14 05:05
is this still an issue i reverted back as well and it worked fine but i updated from windows 10 to 11 and i think my drivers updated and i got a fully new kohya zip and re installed it and it works but it says like 300hours for 2500 steps lol.

**Comment by bmaltais** [comment] 2023-06-14 09:52
Make sure to install CUDA 11.8 drivers

**Comment by rehvka** [comment] 2023-06-15 01:51
hello, same issue here! I followed @bmaltais youtube guide for lycoris training TO THE LETTER, and it took 4 hours of training! instead of the 12-15 minutes it took him. First of all I have a 3080, I think I have everything set up (I'll put a screenshot of what the script detects when I launch it), Re-installed a few times and still slow. I thought it could be my dataset (images too large) so I resized them to 512x512 just in case.. and still 3 hours and a half. 
I am very sorry to bother with such a questions, I am just very ignorant when it comes to codding. Is there a way to rule out problems?, thanks!
![image](https://github.com/bmaltais/kohya_ss/assets/133486469/ce072365-c9ea-45cf-92db-1247db1e9e35)

**Comment by bmaltais** [comment] 2023-06-16 00:07
Try re-installing wioth torch 1... Everything look good so I have no idea why it would be so slow... How big is your dataset? How many repeats? Perhaps you are training a large dataset?

**Comment by rehvka** [comment] 2023-06-16 05:49
@bmaltais I followed your video on youtube about lycoris (thank you for those videos btw, very very helpful for newbies like me), Same number of images, same steps, everything, I downloaded images from instagram so they are not very large, and I even resized them to 512x512 just in case. A friend of mine pointed to me that the last few Nvidia drivers were faulty, so I am gonna reroll them back to see if that helps

**Comment by Kr01iKs** [comment] 2023-06-19 22:10
Same problem. Has anyone fixed it?

**Comment by bmaltais** [comment] 2023-06-20 01:41
someone mentionned trying to install bitsandbytes-windows... might help...

activate the venv (`.\venv\scripts\activate.bat`)
`pip install bitsandbytes-windows`

Hope it help.

**Comment by wenwenwennnnn** [comment] 2023-06-20 06:29
> hello, same issue here! I followed @bmaltais youtube guide for lycoris training TO THE LETTER, and it took 4 hours of training! instead of the 12-15 minutes it took him. First of all I have a 3080, I think I have everything set up (I'll put a screenshot of what the script detects when I launch it), Re-installed a few times and still slow. I thought it could be my dataset (images too large) so I resized them to 512x512 just in case.. and still 3 hours and a half.
> 很抱歉打扰到这样的问题，我只是在codding方面非常无知。有办法排除问题吗？，谢谢！
> ![图像](https://user-images.githubusercontent.com/133486469/245970916-ce072365-c9ea-45cf-92db-1247db1e9e35.png)

I also have the same problem. After updating kohya, it will appear as headless: false. It can be normal started and trained normally, but training speed is extremely slow. Before update, a lora 5000 steps about an hour, after update showed need to 10 hours. Anyone can solve this problem? I use pytorch 2.0

**Comment by bmaltais** [comment] 2023-06-20 10:59
I am not sure what is the cause of the slow speed for some user. I have not observed this on me system. Probably a combination of drivers version and hardware. I suggest you go back to the release you used to run until this is fixed in a future release.

`git checkout <release name like v20.5.2>`

**Comment by evanheckert** [comment] 2023-06-26 20:53
I'm having the same experience - even tried rolling back to the last version that was working well for me. Still getting a speed of 24 seconds per item on a 3070, which is nearly 100x slower than before.

Since rolling back the kohya_ss version didn't fix it either, the other thing that has changed is the nvidia driver. I'm currently on game ready driver v536.23, and still getting the slow speeds. Is there a known working driver version?

**Comment by pulth** [comment] 2023-06-29 19:45
So, I got a decent speed now. What I did was to install with pytorch 1 instead of 2 and use a lower number of total steps. Training for characters works fine now, although it takes at least one hour using DAdaptation to get good results.

**Comment by Warleroux** [comment] 2023-07-17 20:38
It appears to be a common issue. RTX 3060 in my case. Same general issue as other posts. Ridiculously long training. I'd love to here about any other suggestions. In my case I upgraded to torch 2 to try to improve speeds an in short "nope". Thanks

**Comment by bmaltais** [comment] 2023-07-18 12:20
This is kind of frustrating... One thing I could suggest is to go back to a previous release that used to work, delete the venv folder and redo setup. If things are still slow then it is related to a change outside kohya_ss

**Comment by E2GO** [comment] 2023-07-20 15:35
Same issue on 4090 also

**Comment by evanheckert** [comment] 2023-07-20 16:51
Fixed for me, so hopefully this helps others.

1. Uninstall Cuda toolkit and display drivers
2. **Remove environment variables related to cuda**
3. Make sure all Cuda related folders are deleted in program files
4. Download Cuda toolkit (I chose 11.8) and install, including display drivers that come with the installer
5. Delete venv folder and the pycache folder
6. Run setup, using torch 2.

I think it was environmental variables, where I still had traces of a previous 12.1 install. After following the above steps, everything works perfectly!

**Comment by Warleroux** [comment] 2023-07-20 20:38
Awesome.  Ill try it.  I have zero patience to watch the technological paint dry lol. Can you elaborate on the environmental variables you addressed? My experiments have angered something hahaha

**Comment by evanheckert** [comment] 2023-07-20 21:59
Sure, I can help you with that. Here are the steps on how to edit or delete environment variables in Windows:

1. Open the Control Panel.
2. Go to System and Security > System.
3. Click the Advanced system settings link.
4. In the System Properties window, click the Environment Variables button.
	* In the Environment Variables window, there are two sections: **User variables for <current user name> and System variables.
	* User variables are for the current user only.
5. System variables are for all users on the computer.
6. To edit a variable, select the variable and click Edit.
	* In the Edit window, you can change the name and value of the variable.
7. To delete a variable, select the variable and click Delete.
8. Click OK to save your changes.

**Comment by mbastias** [comment] 2023-07-21 14:17
I'm having this problem but in a weird way on Windows. I reinstalled twice now, and after that I get a speed of 2.x it/s. I shutdown the PC for the day, I come back next day, run a training (similar params), and it goes back to slow 1.5 s/it. Any ideas what Windows could be doing that makes the speed go down like that?

**Comment by Warleroux** [comment] 2023-07-21 21:00
Thanks man. Ill giver a go:)

**Comment by Warleroux** [comment] 2023-07-22 04:50
Update on my end. Evanheckert's suggestion including the removal of environmental variables fixed my issue. Thank you for the insights.

**Comment by mbastias** [comment] 2023-07-23 21:59
Ok, not to leave it hanging, I think my problem is related to a bad SD webui installation, I noticed that is not using its venv and in turn is installing packages on the python folder. So, there might be some kind of conflict, I've been narrowing down what helps my speed, and just running the installation again or copying the cudnn files again seems to solve it most of the time.

**Comment by tobi-sp** [comment] 2023-07-24 07:59
Posting this here as it is somewhat related. Same case as OP, tried the solution by evanheckert but sadly it only worked half way:. I had no environmental variables left to delete after uninstalling cuda 12.1, but downgrading to 11.8 helped to get to normal speeds (10 it/s, 3080) for one training. 
When starting another (LoHa) training, speeds are very slow (80s/it) and I need to restart PC (gui only doesnt help). So I guess this also points to something outside the gui being the problem?

**Comment by mbastias** [comment] 2023-07-26 05:10
Ok, I kept trying things out and I've discovered that at least sometimes, this might be a video memory issue. I have a 3070ti which has 8GB. So previously I wasn't able to run more than batch 2 at Adam8bit or I got a OOM error, because my limit was the physical 8GB. But lately with DadaptAdam, on my previous setup (I changed drives and formatted) I was running batch 3 and it seemed to work fine. So, while I was looking at the Task Manager just now, I noticed that the LoRA I'm currently training was using Shared GPU memory, so RAM, and it was obviously bottlenecking the speed and event halting it. The solution on this case was lowering the batch size from 3 to 2. I don't know if that could be tobi-sp second run case too.

**Comment by AIrtistry** [comment] 2023-07-28 15:36
> Fixed for me, so hopefully this helps others. (Note: Running Windows 11, RTX 3070)
> 
> 1. Uninstall Cuda toolkit and display drivers
> 2. **Remove environment variables related to cuda**
> 3. Make sure all Cuda related folders are deleted in program files
> 4. Download Cuda toolkit (I chose 11.8) and install, including display drivers that come with the installer
> 5. Delete venv folder and the pycache folder
> 6. Run setup, using torch 2.
> 
> I think it was environmental variables, where I still had traces of a previous 12.1 install. After following the above steps, everything works perfectly!

I try this solution but its not working :(

**Comment by tobi-sp** [comment] 2023-08-01 10:28
> Ok, I kept trying things out and I've discovered that at least sometimes, this might be a video memory issue. I have a 3070ti which has 8GB. So previously I wasn't able to run more than batch 2 at Adam8bit or I got a OOM error, because my limit was the physical 8GB. But lately with DadaptAdam, on my previous setup (I changed drives and formatted) I was running batch 3 and it seemed to work fine. So, while I was looking at the Task Manager just now, I noticed that the LoRA I'm currently training was using Shared GPU memory, so RAM, and it was obviously bottlenecking the speed and even halting it. The solution on this case was lowering the batch size from 3 to 2. I don't know if that could be tobi-sp second run case too. But why is it going there to start with, is accelerator mixing the memories up?
> 
> Edit: I kept testing this and seems to be that on my case, as soon as the Shared memory gets used the speed gets affected, the more is used, the slower it gets. But as I said, the behavior before was to give an error if the card memory wasn't enough, now is allocating from both places. Anything I can do to change that?

Was able to recreate this now. As soon as there is something in the shared GPU memory it crashes/doesnt continue with training. Im pretty sure I had like 1 or 2 GB in shared memory in earlier versions though...

**Comment by Zorgonaute84** [comment] 2023-08-06 17:57
I also have the issue during Lora training. I fixed it by : 
- Restarting the PC
- Try again -> Same issue
- Launch a textual inversion -> Same issue
- Launch a textual inversion (without bucket and 1epoch only) -> fixed, it train speed again
- Stop Textual Inversion Training
- Launch the Lora training -> Perfect, speed is back

After some training, the issue appear again... I repeat the same process, and the speed came back again.

**Comment by tobi-sp** [comment] 2023-08-06 21:32
Quick update for the failed loHa training on my side: After I found this #1291 , I switched to this specific kohya_ss version and in combination with the 531.68 driver, training works again. I tried other older versions and they didnt work, so what I got from this is that there are some bitsandbytes related problems apparently.

**Comment by mbastias** [comment] 2023-08-06 23:41
> > Ok, I kept trying things out and I've discovered that at least sometimes, this might be a video memory issue. I have a 3070ti which has 8GB. So previously I wasn't able to run more than batch 2 at Adam8bit or I got a OOM error, because my limit was the physical 8GB. But lately with DadaptAdam, on my previous setup (I changed drives and formatted) I was running batch 3 and it seemed to work fine. So, while I was looking at the Task Manager just now, I noticed that the LoRA I'm currently training was using Shared GPU memory, so RAM, and it was obviously bottlenecking the speed and even halting it. The solution on this case was lowering the batch size from 3 to 2. I don't know if that could be tobi-sp second run case too. But why is it going there to start with, is accelerator mixing the memories up?
> > Edit: I kept testing this and seems to be that on my case, as soon as the Shared memory gets used the speed gets affected, the more is used, the slower it gets. But as I said, the behavior before was to give an error if the card memory wasn't enough, now is allocating from both places. Anything I can do to change that?
> 
> Was able to recreate this now. As soon as there is something in the shared GPU memory it crashes/doesnt continue with training. Im pretty sure I had like 1 or 2 GB in shared memory in earlier versions though...
> 
> Edit: Using DDU to uninstall nvidia driver and going with 531.68 solved it for me. Even with shared memory it's fast again. Edit2: But still, my trained LoHa has no effect. Previously trained lohas are still working...

I tried going back on card drivers and I can observe two changes. Memory allocation is way more efficient; I'm using less VRAM per-training. Shared memory seems to have less of an influence on the speed and speed seems to be going up during the training and with latest drivers it used to go down instead.

**Comment by Thom293** [comment] 2023-08-07 01:59
tagging this.

**Comment by brianiup** [comment] 2023-08-09 15:46
nVIDIA put out new windows drivers yesterday (8/8) tried them today and so far they are working MUCH better, however I 've noticed that the CUDA usage will stay 90-100% for a while then drop to like 60% for a while then go back up to the 90's and keep repeating that cycle, is there anything you can do to make sure it's using the cores as efficiently as possible?

**Comment by atomantic** [comment] 2023-08-09 17:04
A lot of variables here so this is an itemization of my journey to get from 12s/it, to 6.2s/it -- TL;DR is that `Torch 1` might be a good first thing to try.

Windows 11, Nvidia 3090 RTX, GeForce Game Ready Driver 535.98

- Seeing  `12s/it` on 12 images with SDXL lora training.
- Noticed I was using python 3.11.0, which had a subtle error message that I overlooked. 
- deleted venv
- Installed python 3.10.9 
- install via ./setup.bat (answered with all defaults)
- same result (12s/it)
- updated Game Ready Driver to 536.99
- same result (12s/it)
- started over with **Torch 1** (renamed venv to venv_torch2 and did a new run of setup.bat, choosing torch 1 but everything else defaults)
- gui errored with `module 'os' has no attribute 'statvfs'` so I did `pip install --upgrade aiofiles` to fix
- ran training again and got `6.2s/it`! -- still 4 hours estimated, which isn't great but it's better than 8 hours...

**Comment by DarkAlchy** [comment] 2023-08-11 04:51
I have not tried the drivers just released as I just rolled back to 531.61 and my 4090 is still very unhappy, as I am.   As a test I tried 1 image with 1 repeat to see 1.25-1.5s/it.  Something, somewhere is seriously wrong.
![image](https://github.com/bmaltais/kohya_ss/assets/10561690/2afbc55d-4dd9-4ada-b233-6ed49c3b8cdd)

**Comment by DarkAlchy** [comment] 2023-08-11 11:09
Here are some hard ass numbers.   This is the same dataset, same everything, only this is local 4090 vs a Colab T4.  WATAF?

4090
![image](https://github.com/bmaltais/kohya_ss/assets/10561690/a21cb77e-81d2-440f-b3e0-4d5a4db813e9)
Colab T4
![image](https://github.com/bmaltais/kohya_ss/assets/10561690/9a2d4833-571d-4ae4-ac77-426851b66389)

**Comment by SamiMertDemir** [comment] 2023-08-18 08:05
> I also have the issue during Lora training. I fixed it by :
> 
> * Restarting the PC
> * Try again -> Same issue
> * Launch a textual inversion -> Same issue
> * Launch a textual inversion (without bucket and 1epoch only) -> fixed, it train speed again
> * Stop Textual Inversion Training
> * Launch the Lora training -> Perfect, speed is back
> 
> After some training, the issue appear again... I repeat the same process, and the speed came back again.
> 
> Edit : I noticed that the issue appear when I tried my Lora with InvokeAI

Thank you ! I can confirm this method works for now :)

**Comment by oranwav** [comment] 2023-08-28 22:07
> Fixed for me, so hopefully this helps others. (Note: Running Windows 11, RTX 3070)
> 
> 1. Uninstall Cuda toolkit and display drivers
> 2. **Remove environment variables related to cuda**
> 3. Make sure all Cuda related folders are deleted in program files
> 4. Download Cuda toolkit (I chose 11.8) and install, including display drivers that come with the installer
> 5. Delete venv folder and the pycache folder
> 6. Run setup, using torch 2.
> 
> I think it was environmental variables, where I still had traces of a previous 12.1 install. After following the above steps, everything works perfectly!

Cheers Mate! Hi, this is I from the future, mid august 23, wanted to say this is still saving lives and GPU time. 
You are a chad.

**Comment by oranwav** [comment] 2023-08-29 11:42
> 

Because i'm back at 1sec/it.... now.
What are you talking about?

**Comment by oranwav** [comment] 2023-08-29 11:44
> Why are people still happy with the speeds they are getting? Are you getting 35-57% faster speeds than a 3090? If not then you need to be very angry as I am.

Because im back to 1sec/it... (im on 3080ti)
That is NOT slow my friend.

**Comment by evanheckert** [comment] 2023-08-29 16:51
> @evanheckert Thumbs down me all you like, but I own a 4090, and I have done the testing and the truth hurts. Thumbs down the messenger for telling you straight up facts, else it shows you are biased on a good day.
> 
> What is your major malfunction with what I said? You have a 4090 too and are so upset you just had to thumbs down the lone voice in the Jensen woods? smh.

I missed the context from your previous post. It sounded like someone just dissing on free open source software without trying to help identify and resolve the problem, which always grinds my gears.

I'll retract my thumbs down, now that I see you've shared a lot of information about your issue.

**Comment by DarkAlchy** [comment] 2023-08-29 17:58
> > @evanheckert Thumbs down me all you like, but I own a 4090, and I have done the testing and the truth hurts. Thumbs down the messenger for telling you straight up facts, else it shows you are biased on a good day.
> > What is your major malfunction with what I said? You have a 4090 too and are so upset you just had to thumbs down the lone voice in the Jensen woods? smh.
> 
> I missed the context from your previous post. It sounded like someone just dissing on free open source software without trying to help identify and resolve the problem, which always grinds my gears.
> 
> I'll retract my thumbs down, now that I see you've shared a lot of information about your issue.

Thank you, as I love OSS, and especially OSH, but as my experiment shows something isn't right.  We do know Nvidia has some issues to be addressed in a future update concerning memory management they now do.  This slow issue is ADA across the board from the 6000 ADA to 4090 and 4080.  The other cards I am unsure about.  What I showed is something changed with the Kohya setup when XL version was released.  I am unsure what it could be though as I am just showing that something is indeed not right.  When you pay 1200, 1700, 5-6k for an ADA card and they are all about, or slower, than a previous gen something is seriously wrong.  My hope is it works itself out as 1700 dollars to get slower than my friend's 3090 really is bad.

**Comment by DarkAlchy** [comment] 2023-08-29 18:03
> > Why are people still happy with the speeds they are getting? Are you getting 35-57% faster speeds than a 3090? If not then you need to be very angry as I am.
> 
> Because im back to 1sec/it... (im on 3080ti) That is NOT slow my friend.

As I said I hope it gets sorted out, but I was talking about the ADA card holders seemingly fine with being slower than last gen not last gen cards.  My friend never saw a slow down on his 3090 with the same 2.1 size.  If you increase to XL size then I expect it to be slower so that isn't what I mean.

Are you saying that same size training suddenly your 3080ti became slower?  If that is the case then, yeah, the steps mentioned might speed you up.  Now if you mean you went from 1.5/2.1 size to XL size and became slower just remember 1.5 to XL size is four times the amount of info being handled.

**Comment by evanheckert** [comment] 2023-08-30 01:33
> > Why are people still happy with the speeds they are getting? Are you getting 35-57% faster speeds than a 3090? If not then you need to be very angry as I am.
> 
> Because im back to 1sec/it... (im on 3080ti) That is NOT slow my friend.

To be fair, @oranwav, I do get 2.4 it/sec on my 3070, that's with 512x512 with a batch size of 2, FWIW, so not sure it's an apples-to-apples rate comparison.

**Closed** 2024-01-29 00:25 UTC
