### ISSUE TITLE
Your Linux installation is wrong

### ISSUE THREAD

**Issue by kopyl** [bmaltais/kohya_ss#526] opened 2023-04-02 22:56 UTC
I still have to manually do

- `cd kohya_ss`
- `pip install -U -r requirements.txt`
- `pip unstall xformers==0.0.18`
- `apt-get install libgl1 -y`
- `apt-get install libglib2.0-0 -y`
- `apt-get install python3-tk -y`

Why???
Could you please post a setup script which actually installs working GUI???
you can reference my Docker image i built for your gui – kopyl/loratrainer

**Comment by bmaltais** [comment] 2023-04-02 23:15
Hello @kopyl 

Linux support is fairly new and @jstayco has been diligently working on it for the past few days. I suggest you bring the issues to him so he can improve the installation script.

I just pushed a new release... hoping it help address the issues you have observed.

**Comment by jstayco** [comment] 2023-04-02 23:19
apt-get install libgl1 -y
apt-get install libglib2.0-0 -y

^ I don't think I've seen these referenced before. Is there something unique to your setup or a specific function these packages enable?

**Comment by kopyl** [comment] 2023-04-02 23:22
@jstayco nope. When I run it on runpod.io , i see errors that only these 2 commands can fix.

**Comment by jstayco** [comment] 2023-04-02 23:25
I don't have runpod myself. So is that something specific to their environment? I already have checks for runpod vs bare metal/VM. I don't think it'll hurt the users who haven't mentioned it, so it should be an easy add.

I also see this line: pip unstall xformers==0.0.18

Which I also haven't seen any users mention before. I was under the impression runpod environment used Nvidia GPUs (and so that package helps speed up some operations).

**Comment by kopyl** [comment] 2023-04-02 23:31
I need to install xformers in order to do `python tools/cudann_1.8_install.py`

When I run `python tools/cudann_1.8_install.py`, i get some error which can only installing xformers fix.

But i think xformers is needed for something else to run LoRA GUI as well (but not 100% sure).

Will answer on the rest of your questions later, ok?

**Comment by jstayco** [comment] 2023-04-02 23:35
I may have found your issue. You're describing a lot of things our new install script handles. Try simply running setup.sh. It should auto detect your runpod environment and even launch the GUI for you.  Check the README or run setup -h for more info.

But that install line is already in there: https://github.com/bmaltais/kohya_ss/blob/master/setup.sh#L464

**Comment by kopyl** [comment] 2023-04-03 01:24
@jstayco 

> is that something specific to their environment?
I doubt it.

> haven't mentioned it
haven't mentioned what?

> runpod environment used Nvidia GPUs
runpod environment does use Nvidia GPUs

> Are you using machines that don't have that package?
I guess it's not installed by default

> If you keep it
keep what?

**Comment by kopyl** [comment] 2023-04-03 03:06
@kopyl 

> I think you may be trying to bypass that and run things manually.

Nope, i just ran `setup.sh`, but was still required to install those other things manually after `setup.sh` was finished running.

> It should auto detect your runpod environment and even launch the GUI for you

No, thanks, i only need the installation. How to avoid launching the GUI?

> `setup.sh -p`

I ran `setup.sh -r`, did not try `setup.sh -p`

> that install line is already in there

So why do I still need to install the `python3-tk` manually?

**Comment by kopyl** [comment] 2023-04-03 03:07
@bmaltais 

> I just pushed a new release...

I tried running that `setup.sh` about 30 mins before you pushed it... What did you change?

**Comment by bmaltais** [comment] 2023-04-03 03:16
@jstayco pushd an update. I don't really maintain the linux or macos code. I accept code merge for other platform than WIndows to help others out there. This is still early days and support for linux and macos is still being worked out... so it will likelly fail for a while while kinks are worked out.

**Comment by kopyl** [comment] 2023-04-03 03:18
@jstayco here what i get:

```root@1794abe90a99:/kohya_ss# ./setup.sh
Creating install folder /workspace/kohya_ss.
Attempting to clone https://github.com/bmaltais/kohya_ss.git.
Cloning into 'kohya_ss'...
remote: Enumerating objects: 2397, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 2397 (delta 0), reused 1 (delta 0), pack-reused 2393
Receiving objects: 100% (2397/2397), 3.41 MiB | 11.44 MiB/s, done.
Resolving deltas: 100% (1620/1620), done.
Already on 'master'
Installing Python TK if not found on the system.
Switching to virtual Python environment.
Checking for pip updates before Python operations.
Installing python dependencies. This could take a few minutes as it downloads files.
If this operation ever runs too long, you can rerun this script in verbose mode to check.
Installing tenssort.
Removing the temp requirements file.
Exiting Python virtual environment.
Checking symlinks now.
Checking symlinks now.
Linking libnvinfer_plugin.so.7.
Checking symlinks now.
Linking libnvinfer.so.7.
Checking symlinks now.
Linking libcudart.so.11.0.
Copying accelerate config file to: /root/.cache/huggingface/accelerate/default_config.yaml
/workspace/kohya_ss/gui.sh: line 4: ./venv/bin/activate: No such file or directory
Validating that requirements are satisfied.
ERROR: Could not detect requirement name for 'git+https://github.com/KohakuBlueleaf/LyCORIS.git@c3d925421209a22a60d863ffa3de0b3e7e89f047', please specify one with #egg=your_package_name

[notice] A new release of pip available: 22.2.1 -> 23.0.1
[notice] To update, run: pip install --upgrade pip
Error: The following packages are missing:
 - accelerate==0.15.0
 - albumentations==1.3.0
 - altair==4.2.2
 - bitsandbytes==0.35.0
 - dadaptation==1.5
 - diffusers[torch]==0.10.2
 - easygui==0.98.3
 - einops==0.6.0
 - ftfy==6.1.1
 - gradio==3.19.1; sys_platform != 'darwin'
 - lion-pytorch==0.0.6
 - opencv-python==4.7.0.68
 - pytorch-lightning==1.9.0
 - safetensors==0.2.6
 - tensorboard==2.10.1 ; sys_platform != 'darwin'
 - tk==0.1.0
 - toml==0.10.2
 - transformers==4.26.0
 - voluptuous==0.13.1
 - fairscale==0.4.13
 - requests==2.28.2
 - timm==0.6.12
 - huggingface-hub==0.12.0; sys_platform != 'darwin'
 - tensorflow==2.10.1; sys_platform != 'darwin'
 - lycoris-lora @ git+https://github.com/KohakuBlueleaf/LyCORIS.git@c3d925421209a22a60d863ffa3de0b3e7e89f047

Run upgrade.sh or pip install -U -r requirements.txt to resolve the missing requirements listed above...
Setup finished! Run ./gui.sh to start.
Please note if you'd like to expose your public server you need to run ./gui.sh --share
root@1794abe90a99:/kohya_ss#```

**Comment by kopyl** [comment] 2023-04-03 03:23
@jstayco why the hell you don't include `pip install -U -r requirements.txt` in the setup? o_O

**Comment by bmaltais** [comment] 2023-04-03 03:26
Look like there is an issue with the venv... possibly related to the platform you are running the script on:

`/workspace/kohya_ss/gui.sh: line 4: ./venv/bin/activate: No such file or directory`

**Comment by kopyl** [comment] 2023-04-03 03:30
@jstayco why the heck do you update the git?

> Updating: https://github.com/bmaltais/kohya_ss.git

Please remove this, i want to make sure that if i have a stable version, it will certainly not download any broken one.

**Comment by kopyl** [comment] 2023-04-03 03:31
> Look like there is an issue with the venv.

Nobody in Docker uses venv, so the script should not break because of this. And if it does, it should be mentioned that installation requires it.

**Comment by kopyl** [comment] 2023-04-03 03:32
@jstayco here is another set of logs after installing requirements manually:

```
root@1794abe90a99:/kohya_ss# ./setup.sh
Attempting to clone https://github.com/bmaltais/kohya_ss.git.
git repo detected. Attempting to update repository instead.
Updating: https://github.com/bmaltais/kohya_ss.git
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint:
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint:
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
From https://github.com/bmaltais/kohya_ss
 * branch            master     -> FETCH_HEAD
Already on 'master'
Installing Python TK if not found on the system.
Switching to virtual Python environment.
Checking for pip updates before Python operations.
Installing python dependencies. This could take a few minutes as it downloads files.
If this operation ever runs too long, you can rerun this script in verbose mode to check.
Installing tenssort.
Removing the temp requirements file.
Exiting Python virtual environment.
Checking symlinks now.
Checking symlinks now.
libnvinfer_plugin.so.7 symlink looks fine. Skipping.
Checking symlinks now.
libnvinfer.so.7 symlink looks fine. Skipping.
Checking symlinks now.
libcudart.so.11.0 symlink looks fine. Skipping.
Copying accelerate config file to: /root/.cache/huggingface/accelerate/default_config.yaml
/workspace/kohya_ss/gui.sh: line 4: ./venv/bin/activate: No such file or directory
Validating that requirements are satisfied.
All requirements satisfied.
Traceback (most recent call last):
  File "/kohya_ss/kohya_gui.py", line 4, in <module>
    from dreambooth_gui import dreambooth_tab
  File "/kohya_ss/dreambooth_gui.py", line 13, in <module>
    from library.common_gui import (
  File "/kohya_ss/library/common_gui.py", line 1, in <module>
    from tkinter import filedialog, Tk
  File "/usr/local/lib/python3.10/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: libtk8.6.so: cannot open shared object file: No such file or directory
Setup finished! Run ./gui.sh to start.
Please note if you'd like to expose your public server you need to run ./gui.sh --share
root@1794abe90a99:/kohya_ss#
```

**Comment by kopyl** [comment] 2023-04-03 03:34
@jstayco with this Dockerfile everything works perfectly:

```
FROM python:3.10.6-slim

WORKDIR /

COPY v1-5-pruned.ckpt v1-5-pruned.ckpt

RUN apt update && apt install -y git
RUN apt install python3-pip python3-setuptools python3-dev python3-venv python3-wheel -y
RUN apt install wormhole -y
RUN pip install -U pip setuptools
RUN apt-get install python3-tk -y
RUN apt-get install unzip
RUN apt install nano

RUN apt-get install libgl1 -y
RUN apt-get install libglib2.0-0 -y


COPY kohya_ss kohya_ss
COPY mwxKTEtelILoIbMbruuM.zip mwxKTEtelILoIbMbruuM.zip
RUN unzip mwxKTEtelILoIbMbruuM.zip -d kohya_ss/
COPY config-files/default_config.yaml /root/.cache/huggingface/accelerate/default_config.yaml

WORKDIR kohya_ss
RUN pip install -U -r requirements.txt
RUN bash ubuntu_setup.sh
RUN python tools/cudann_1.8_install.py

RUN rm /mwxKTEtelILoIbMbruuM.zip
RUN echo "alias l='ls \$LS_OPTIONS -a'" >> ~/.bashrc

ENV PYTHONUNBUFFERED=1
CMD ["sleep", "infinity"]
```

**Comment by jstayco** [comment] 2023-04-03 03:55
That's still using the old Ubuntu

**Comment by jstayco** [comment] 2023-04-03 04:04
If you replace the contents of your gui.sh with this code below and then run the setup.sh does it work? I know runpod is a docker environment, so if you can't test just let me know and I'll throw up the PR, so it can be merged to /dev and you can test that way. (You can specify branches via command line like such: setup.sh -p -r -b dev)
```
# This gets the directory the script is run from so pathing can work relative to the script where needed.
SCRIPT_DIR="$(cd -- $(dirname -- "$0") && pwd)"

# Activate the virtual environment
source "$SCRIPT_DIR/venv/bin/activate"

# If the requirements are validated, run the kohya_gui.py script with the command-line arguments
if python tools/validate_requirements.py; then
    python "$SCRIPT_DIR/kohya_gui.py" "$@"
fi
```

**Comment by jstayco** [comment] 2023-04-03 04:05
For what it's worth, while we're discussing this and I'm trying to fix what is there currently, I am also working on a unified installer that will work the same way for Windows, macOS, and various Linux distros. We'll get there 😄

**Comment by jstayco** [comment] 2023-04-03 05:02
> @jstayco why the hell you don't include `pip install -U -r requirements.txt` in the setup? o_O

There's a lot going on with your attitude. You do realize I'm trying to introduce an installer that previously simply didn't exist? 

And to answer your rude question about cloning git? It's answered in documentation: https://github.com/bmaltais/kohya_ss#linux-and-macos

And, lastly, we do call pip operations: https://github.com/bmaltais/kohya_ss/blob/master/setup.sh#L215

**Comment by bmaltais** [comment] 2023-04-03 14:41
@jstayco I switched to that because users were complaining they could not use the standard ==0.1.4 syntax. Perhaps the issue is now resolved and we can go back to the standard notation instead of the hack I did in the requirements file... try commenting the offending line and uncomment the lycoris line.

**Comment by kopyl** [comment] 2023-04-03 15:04
@jstayco i don't want to mess with venv. It's not needed in Docker and only introduces redundant complexity.

**Comment by kopyl** [comment] 2023-04-03 15:19
> answer your rude question

Sorry. But what was the question?

**Comment by glentner** [comment] 2024-01-25 03:33
Woof - god forbid people put their work out on the internet for all to use and get berated by a random person that it isn't perfect for them specifically in the moment they try to use it. From what I can tell this was pilot error, and yet you all still try to help, impressive.

**Closed** 2024-01-29 00:22 UTC
