### ISSUE TITLE
This utility can extract a LyCORIS LoCon network from a finetuned model.

### ISSUE THREAD

**Issue by Dervlex** [bmaltais/kohya_ss#1404] opened 2023-08-18 12:34 UTC
ModuleNotFoundError: No module named 'lycoris.kohya_model_utils'

Could you fix this issue ?

**Comment by astro9ine** [comment] 2023-08-18 20:18
same, still haven't been fixed

**Comment by bmaltais** [comment] 2023-08-18 23:14
The challenge is that I can't reproduce the issue on my system. All work fine. So it must be caused by some configuration specific to a few users Windows environments.

If the cause is ever discovered and the fix found I will try to bake it in the code. But at the moment this issue appear to be restricted to only a few systems.

**Comment by Dervlex** [comment] 2023-08-19 12:50
> The challenge is that I can't reproduce the issue on my system. All work fine. So it must be caused by some configuration specific to a few users Windows environments.
> 
> If the cause is ever discovered and the fix found I will try to bake it in the code. But at the moment this issue appear to be restricted to only a few systems.
> 
> Are you running on windows 10, windws 11, Linux?\

Maybe its because you updating after each update just the folder with all modules ? So maybe you could reproduce the error if you create a new folder and use the "git" command with cmd again ? I guess the modules for this extension just didnt get downloaded right... or could you please upload your module folder ? Where the lycoris stuff should be?

**Comment by bmaltais** [comment] 2023-08-19 14:37
The lycoris tools can be a pain as the internal module structure has changed... let me check... I don't use lycoris much anymore since I moved to SDXL training... so I might have missed that one.

**Comment by bmaltais** [comment] 2023-08-19 14:49
Found a missing update from the LyCORIS repo. I have pushed the fix to the dev2 branch. Give it a try.

**Comment by Zokreb** [comment] 2023-08-19 16:08
I just tried on my side and was able to have it work.
My extracted lyco is complete rubbish though, but that is because there is an issue between the chair and the keyboard ^^

Coucou de France, et encore merci pour ce que tu fais pour la communauté Bernard !!!

**Comment by astro9ine** [comment] 2023-08-19 19:27
> The challenge is that I can't reproduce the issue on my system. All work fine. So it must be caused by some configuration specific to a few users Windows environments.
> 
> If the cause is ever discovered and the fix found I will try to bake it in the code. But at the moment this issue appear to be restricted to only a few systems.
> 
> Are you running on windows 10, windws 11, Linux?\

i',m running on Runpod and have the issue

**Comment by bmaltais** [comment] 2023-08-20 01:34
> > The challenge is that I can't reproduce the issue on my system. All work fine. So it must be caused by some configuration specific to a few users Windows environments.
> > If the cause is ever discovered and the fix found I will try to bake it in the code. But at the moment this issue appear to be restricted to only a few systems.
> > Are you running on windows 10, windws 11, Linux?\
> 
> i',m running on Runpod and have the issue

Have you tried the dev2 branch version?

```
git checkout dev2
git pull
./gui.sh

**Comment by Dervlex** [comment] 2023-08-22 08:31
> Found a missing update from the LyCORIS repo. I have pushed the fix to the dev2 branch. Give it a try.

I will also try it out in a minute ! 

But first of all, thank you very much for all of your work ! 
Your crazy ^^ 

And are you getting paied ? Or do you have a patreon to pay you something ?

**Comment by Dervlex** [comment] 2023-08-22 08:55
Working ! Thx mate!

**Closed** 2024-01-29 00:27 UTC
