### ISSUE TITLE
I trained the finetune model for 12 hours. @_@ Look what the result is

### ISSUE THREAD

**Issue by WagnerFighter** [bmaltais/kohya_ss#1711] opened 2023-11-26 02:17 UTC
**Why such a terrible result?** I kind of wrote captions and tags, 85 images of 200 epochs for each trained with learning rate 1e-07.
[last_20231125-090842.json](https://github.com/bmaltais/kohya_ss/files/13465728/last_20231125-090842.json)
[meta_cap.json](https://github.com/bmaltais/kohya_ss/files/13465729/meta_cap.json)
[meta_lat.json](https://github.com/bmaltais/kohya_ss/files/13465730/meta_lat.json)
I write "illumination halo" in a negative prompt and there is illumination halo on all the pictures that he gives me. Everything is distorted, the picture is kind of ugly.
![grid-0001](https://github.com/bmaltais/kohya_ss/assets/121365756/f7dda0e1-fc43-43ed-9baf-1d60bf3454c4)
![Screenshot_1](https://github.com/bmaltais/kohya_ss/assets/121365756/f037620b-655d-4c24-8826-82bac7fb22bb)
![Screenshot_2](https://github.com/bmaltais/kohya_ss/assets/121365756/81157d71-b2f1-40d5-be48-dd36cb76c0f0)

**Comment by oibox** [comment] 2023-11-27 17:10
It seems like you've overlooked noise offset parameters and overtrained your model.

First is simple either: models tend to generate averagely contrast pictures. It especially present on a monochrome images. Noise offset technique is helping Stable Diffusion to retain high contrast. Follow the manual.

Second is hard: while OFT is not properly working and validation loss is not in master, this is a deal of hit and miss. Do not assume that longer training is better. Find a least undertrained epoch and train again with less learning rate. Repeat until satisfied.

You are using an Adafactor optimizer, and it needs more arguments. If you don't want to fool your head with all the arguments and don't use a very low-VRAM gpu, you should stick to AdamW or AdamW8bit, and use constant scheduler.

Also, finetune models are very sensitive to captions, and result seems to be struggled to converge - maybe you've messed up captions. Try dreambooth or lora instead, use class token in your captions. Using class token of these pictures' style will nicely 'glue' model up, I did it dozens of times.

Check this manual, it has a great deal of insights - https://rentry.org/59xed3#20230308

**Comment by WagnerFighter** [comment] 2023-11-28 01:37
> and result seems to be struggled to converge - maybe you've messed up captions
I double-checked the signatures, but I entered them manually.
If you take the 100th epoch, then there are just gray spots, as if the model is under-trained. It is also strange that this model is trying to copy the faces on which it was trained instead of creating new ones.
I tried to read the instructions, but it is incomprehensibly written there and there are no things that are incomprehensible to me.
I have 4060ti 16gb.
AdamW is consuming 22GB of vram.
AdaFactor - 11gb vram
"AdamW 8bit doesn't seem to work." as written in "Guides" kohya_ss (it says about SDXL, but it doesn’t work for me on v1-5, it gives some errors)
If the model is retrained, its face should not float like that, the picture seems to be glued together from different segments with some kind of strong neural network texture throughout the image. The creator of Realistic Vision told me that he does 200 epochs for each 768x1024 image.

![170109019531170](https://github.com/bmaltais/kohya_ss/assets/121365756/32e9da6a-2dce-4756-970e-4680fc250c38)

**Comment by oibox** [comment] 2023-11-28 02:42
Are you running it on Windows? Then 'ImportError: No bitsandbytes / bitsandbytes' may be resolved with setup.bat in kohya-ss folder. Start it using command line, choose '3. Install specific bitsandbytes version', then choose '4. Install bitsandbytes-windows'. The problem is with the latest versions of Kohya-GUI.

Your model persistently trying to use original parts of images is a typical sign of overtraining.

There is something wrong going on with your configuration. I do this kind of training all the time. I did some nice training with Dadaptation and bigger batch sizes, it is very memory hungry, and I have 16gb gpu, too. To be honest, I don't see any particular problems with your training settings and why is it so hard on hardware. You should add 'relative_step=True scale_parameter=True warmup_init=False' (or warmup_init=True if you are still using 'constant with warmup') in optimizer args and see if it improves something.

You also can download portable version of the last fine kohya-GUI https://github.com/serpotapov/Kohya_ss-GUI-LoRA-Portable

The last thing I can offer is to upload some of your images for inspection and experimentation training. There is no universal settings and it's hard for me to advice something using only my imagination. You can downscale them if you worry about misappropriation.

**Closed** 2024-01-29 00:29 UTC
