### ISSUE TITLE
Setup fails to found a file "\\tools\\config_files\\accelerate\\default_config.yaml"

### ISSUE THREAD

**Issue by tomirasanen** [bmaltais/kohya_ss#918] opened 2023-06-05 04:48 UTC
Steps to reproduce:
- clean install
- run setup.bat in cmd
- choose 1 from the menu
- tried both torch 1 and 2, same error
-------------

Kohya_ss GUI setup menu:

0. Cleanup the venv
1. Install kohya_ss gui
2. Install cudann files
3. Start Kohya_ss GUI in browser
4. Quit

Enter your choice: 1

1. Torch 1
2. Torch 2
3. Cancel

Enter your choice: 1

07:42:04-765295 INFO     Python 3.10.9 on Windows
07:42:04-769296 INFO     nVidia toolkit detected
07:42:05-353306 INFO     Torch 1.12.1+cu116
07:42:05-368318 INFO     Torch backend: nVidia CUDA 11.6 cuDNN 8700
07:42:05-370314 INFO     Torch detected GPU: NVIDIA GeForce RTX 4090 VRAM 24564 Arch (8, 9)
                         Cores 128
07:42:05-386767 INFO     Installing package:
                         https://github.com/C43H66N12O12S2/stable-diffusion-webui/releases/do
                         wnload/f/xformers-0.0.14.dev0-cp310-cp310-win_amd64.whl
07:42:21-041060 INFO     Verifying requirements
07:42:21-046063 INFO     Installing package: .
07:42:23-084220 INFO     Copying bitsandbytes files...
07:42:23-085221 INFO     Configuring accelerate...
╭──────────────────────────── Traceback (most recent call last) ──────
│ F:\KOHYA\kohya_ss\tools\setup_windows.py:666 in <module>                                
│                                                                                          
│   665     setup_logging()                                                               
│ ❱ 666     main_menu()                                                                    
│   667                                                                                   
│                                                                                        
│ F:\KOHYA\kohya_ss\tools\setup_windows.py:643 in main_menu                             
│                                                                                         
│   642                 if choice_torch == '1':                                           
│ ❱ 643                     install_kohya_ss_torch1()                                     
│   644                     break                                                       
│                                                                                          
│ F:\KOHYA\kohya_ss\tools\setup_windows.py:570 in install_kohya_ss_torch1                 
│                                                                                        
│   569     sync_bits_and_bytes_files()                                                   
│ ❱ 570     configure_accelerate()                                                        
│   571     # run_cmd(f'accelerate config')                                              
│                                                                                         
│ F:\KOHYA\kohya_ss\tools\setup_windows.py:151 in configure_accelerate                   
│                                                                                         
│   150             )                                                                   
│ ❱ 151             shutil.copyfile(                                                       
│   152                 source_accelerate_config_file, target_config_location            
│                                                                                        
│ C:\Users\Tomi\AppData\Local\Programs\Python\Python310\lib\shutil.py:254 in copyfile     
│                                                                                       
│    253     else:                                                                        
│ ❱  254         with open(src, 'rb') as fsrc:                                            
│    255             try:                                                                 
╰───────────────────────────────────────────────────────
FileNotFoundError: [Errno 2] No such file or directory:
'F:\\KOHYA\\kohya_ss\\tools\\config_files\\accelerate\\default_config.yaml'

(venv) F:\KOHYA\kohya_ss>

**Comment by Phando** [comment] 2023-06-05 05:21
I was seeingthis error too.
I copied the config_files\accelerate\default_config.yaml folder into tools, everything seems to be working so far...

**Comment by bmaltais** [comment] 2023-06-05 09:42
Darn, I will fix this today. Not sure why I don't see this error.

**Comment by bmaltais** [comment] 2023-06-05 11:17
OK, I was able to reproduc the issue. Hoping to fix this quickly.

**Comment by jwijaya83** [comment] 2023-06-05 18:44
I have a fix for this. Can you add me as contributor to create a PR.

**Closed** 2023-06-05 22:31 UTC
